#!/usr/bin/env bash
# Agent CLI Startup Script — autoharness
#
# This script is a thin compatibility shim: it delegates the entire
# supervised Copilot CLI session lifecycle -- workspace bootstrap, sidecar
# preflight, CLI resolution, spawn, and lifecycle supervision -- to
# `autoharness run`. See src/autoharness/supervise/ (bootstrap.py,
# sidecar.py, resolve.py, app.py) for the implementation this script no
# longer duplicates.
#
# Usage: ./start.sh
#   Requires execute permission on first use: chmod +x start.sh
#
# Generated by autoharness. Re-run install or tune to regenerate.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── GitHub Copilot CLI ──────────────────────────────────────────────────────
# Auto-MergeInstall / Auto-Tune are GLOBAL agents provided by the autoharness
# marketplace plugin. They are the versions used when upgrading autoharness and
# are intentionally NOT copied into this workspace's local agent config -- a
# stale local copy would shadow the global agent during an upgrade. Upgrade
# them globally with `copilot plugin install autoharness@autoharness`.
#
exec autoharness run --workspace "$script_dir" -- "$@"

# ── Claude Code ─────────────────────────────────────────────────────────────
# Uncomment to run Claude Code with workspace-local state directories.
# CLAUDE_CONFIG_DIR redirects Claude's config and history to the workspace.
# Verify that your installed version of Claude Code supports this env variable.
#
# export CLAUDE_CONFIG_DIR="./.claude"
# claude

# ── OpenAI Codex / Agents ────────────────────────────────────────────────────
# Uncomment to run Codex with a workspace-local API key file.
#
# export OPENAI_API_KEY="$(cat .openai-token)"
# codex
