#!/usr/bin/env bash
# Agent CLI Startup Script — autoharness
#
# Sets workspace-local directories so that AI agent state (memories,
# checkpoints, database) is scoped to this workspace and git-visible.
#
# Usage: ./start.sh
#   Requires execute permission on first use: chmod +x start.sh
#
# Activate the section matching your AI CLI tool.
# To switch tools, comment out the active section and uncomment another.
#
# Generated by autoharness. Re-run install or tune to regenerate.

# ── GitHub Copilot CLI ──────────────────────────────────────────────────────
# COPILOT_HOME redirects the Copilot CLI database and memory to a workspace-
# local directory. This keeps agent state visible in git and isolated per
# project rather than shared across all workspaces.
#
# This script does NOT install or refresh Auto-MergeInstall / Auto-Tune.
# Register those globally with `autoharness setup-copilot-cli`.
# Re-run that setup command after upgrading autoharness so updated agent and
# skill files are recopied into the standard Copilot CLI config directory.
#
# COPILOT_EXE_PATH must be an executable path only (no arguments).
# Set ai_tools.copilot_cli.exe_path in .autoharness/config.yaml if copilot
# is not on PATH, then re-run autoharness install or tune.
#
export COPILOT_HOME="./.copilot"
# export ENGRAM_DATA_DIR="./.engram"   # Uncomment when the agent-engram capability pack is active
export GITHUB_TOKEN="$(gh auth token)"
"copilot"

# ── Claude Code ─────────────────────────────────────────────────────────────
# Uncomment to run Claude Code with workspace-local state directories.
# CLAUDE_CONFIG_DIR redirects Claude's config and history to the workspace.
# Verify that your installed version of Claude Code supports this env variable.
#
# export CLAUDE_CONFIG_DIR="./.claude"
# claude

# ── OpenAI Codex / Agents ────────────────────────────────────────────────────
# Uncomment to run Codex with a workspace-local API key file.
#
# export OPENAI_API_KEY="$(cat .openai-token)"
# codex
