# deploy-harness.ps1 — scripted install/deploy for autoharness
#
# Deterministic bootstrap-and-deploy wrapper for autoharness. It collapses the
# scattered "install tool -> register environment -> configure packs -> run
# installer" sequence into one idempotent, documented command, then HANDS OFF
# template composition to the AI-agent installer.
#
# Six phases (decision D2):
#   preflight  -> verify prerequisites (fail closed on missing hard prereqs)
#   bootstrap  -> locate/acquire autoharness_home (global; opt-in via -Bootstrap)
#   register   -> run autoharness setup-* / copilot plugin install
#   scaffold   -> write .autoharness/config.yaml (preset + all packs from registry)
#   compose    -> HANDOFF ONLY: print the /install-harness command; NO template
#                 resolution happens here (that is the agent's job)
#   verify     -> optional deterministic `autoharness verify-workspace`
#
# The scaffold/verify phases write ONLY inside the current workspace (cwd). The
# bootstrap phase installs a GLOBAL tool OUTSIDE cwd BY DESIGN and is therefore
# gated behind an explicit -Bootstrap opt-in. -DryRun prints the plan without
# mutating anything. Single deterministic pass per phase (no internal retry loop).
#
# Idempotent: an existing autoharness_home is detected and reused; an existing
# .autoharness/config.yaml is backed up (timestamped) before overwrite and only
# overwritten with -Force; an existing .env.local is never clobbered.
#
# Exit codes:
#   0  success
#   1  preflight failure (missing hard prerequisite)
#   2  bootstrap failure (autoharness_home not found and not authorized to install)
#   3  register failure
#   4  scaffold failure
#   5  verify failure
#
# Generated by autoharness. Re-run install or tune to regenerate.

[CmdletBinding()]
param(
    [ValidateSet("starter", "standard", "full")]
    [string]$Preset = "full",

    # "all" (resolved from the pack registry) or a comma-separated subset.
    [string]$Packs = "all",

    [ValidateSet("vscode", "copilot-cli", "claude", "codex", "none")]
    [string]$Register = "copilot-cli",

    [ValidateSet("pip", "clone")]
    [string]$InstallMethod = "pip",

    [Alias("Home")]
    [string]$HomePath = "",

    # Explicit opt-in for the out-of-cwd GLOBAL install (D6).
    [switch]$Bootstrap,

    [switch]$DryRun,

    [switch]$Force
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
# Make native (external) commands with a non-zero exit code terminate like a
# throwing cmdlet so the try/catch blocks below detect register/verify/bootstrap
# failures (PowerShell 7.3+; harmlessly ignored on older hosts).
$PSNativeCommandUseErrorActionPreference = $true

$WorkspaceRoot = (Get-Location).Path
$PythonBin = "python"
$AutoharnessHomeDefault = "$HOME/.autoharness"
$PackRegistryRelPath = "templates/packs/capability-pack-registry.yaml"

function Write-Phase([string]$Name) { Write-Host "== $Name ==" -ForegroundColor Cyan }
function Write-Ok([string]$Msg) { Write-Host "  [OK]   $Msg" -ForegroundColor Green }
function Write-Info([string]$Msg) { Write-Host "  [..]   $Msg" }
function Write-Warn2([string]$Msg) { Write-Warning $Msg }
function Write-Fail([string]$Msg) { Write-Host "  [FAIL] $Msg" -ForegroundColor Red }

# Load .env.local (gitignored per-developer overrides) if present, mirroring the
# start.ps1 loader: export each KEY=VALUE only when not already set; strip a
# single pair of matching surrounding quotes.
$envLocalPath = Join-Path $WorkspaceRoot ".env.local"
if (Test-Path -LiteralPath $envLocalPath -PathType Leaf) {
    Get-Content -LiteralPath $envLocalPath | ForEach-Object {
        if ($_ -match '^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*?)\s*$') {
            $name = $matches[1]
            if ($null -eq [Environment]::GetEnvironmentVariable($name, "Process")) {
                $value = $matches[2]
                if ($value.Length -ge 2) {
                    $firstChar = $value[0]
                    $lastChar = $value[$value.Length - 1]
                    if ((($firstChar -eq '"') -or ($firstChar -eq "'")) -and ($lastChar -eq $firstChar)) {
                        $value = $value.Substring(1, $value.Length - 2)
                    }
                }
                [Environment]::SetEnvironmentVariable($name, $value, "Process")
            }
        }
    }
}

function Resolve-AutoharnessHome {
    # Resolution order: -Home flag -> AUTOHARNESS_HOME env -> `autoharness home`
    # CLI -> default. Returns the resolved path or $null if unresolved.
    if ($HomePath) { return $HomePath }
    if ($env:AUTOHARNESS_HOME) { return $env:AUTOHARNESS_HOME }
    $cli = Get-Command autoharness -ErrorAction SilentlyContinue
    if ($cli) {
        try {
            $resolved = (& $cli.Source home 2>$null | Select-Object -First 1)
            if ($resolved) { return $resolved.Trim() }
        } catch { }
    }
    if (Test-Path -LiteralPath $AutoharnessHomeDefault) { return $AutoharnessHomeDefault }
    return $null
}

function Get-RegistryPacks([string]$HomePath) {
    # Enumerate pack ids from the plain-YAML capability-pack registry with a
    # deterministic line scan (no YAML module dependency).
    if (-not $HomePath) { return @() }
    $registryPath = Join-Path $HomePath $PackRegistryRelPath
    if (-not (Test-Path -LiteralPath $registryPath -PathType Leaf)) { return @() }
    $ids = @()
    foreach ($line in Get-Content -LiteralPath $registryPath) {
        if ($line -match '^\s*-\s*id:\s*"([^"]+)"') { $ids += $matches[1] }
    }
    return $ids
}

# ── Phase 1: preflight ──────────────────────────────────────────────────────
function Invoke-Preflight {
    Write-Phase "preflight"
    $hardMissing = @()

    if (Get-Command python -ErrorAction SilentlyContinue) { $script:PythonBin = "python"; Write-Ok "python present" }
    elseif (Get-Command python3 -ErrorAction SilentlyContinue) { $script:PythonBin = "python3"; Write-Ok "python3 present" }
    else { Write-Fail "python missing (required)"; $hardMissing += "python" }
    if (Get-Command git -ErrorAction SilentlyContinue) { Write-Ok "git present" }
    else { Write-Fail "git missing (required)"; $hardMissing += "git" }
    if (Get-Command gh -ErrorAction SilentlyContinue) { Write-Ok "gh present" }
    else { Write-Warn2 "gh not found (optional; needed for PR automation)" }

    switch ($Register) {
        "copilot-cli" { $cliTool = "copilot" }
        "claude" { $cliTool = "claude" }
        "codex" { $cliTool = "codex" }
        default { $cliTool = $null }
    }
    if ($cliTool) {
        if (Get-Command $cliTool -ErrorAction SilentlyContinue) { Write-Ok "$cliTool present" }
        else { Write-Warn2 "$cliTool not found (needed to register the $Register environment)" }
    }

    # Pack MCP prereqs are advisory: the deploy path seeds config and hands off;
    # missing MCP tools do not block scaffolding.
    foreach ($mcp in @("backlogit", "engram")) {
        if (Get-Command $mcp -ErrorAction SilentlyContinue) { Write-Ok "$mcp MCP prereq present" }
        else { Write-Info "$mcp not found (optional pack MCP prereq)" }
    }

    if ($hardMissing.Count -gt 0) {
        Write-Fail ("Missing hard prerequisites: " + ($hardMissing -join ", "))
        return $false
    }
    Write-Ok "preflight passed"
    return $true
}

# ── Phase 2: bootstrap ──────────────────────────────────────────────────────
function Invoke-Bootstrap {
    Write-Phase "bootstrap"
    $resolved = Resolve-AutoharnessHome
    if ($resolved -and (Test-Path -LiteralPath $resolved)) {
        Write-Ok "autoharness_home found: $resolved (reusing; idempotent skip)"
        return $resolved
    }

    Write-Info "autoharness_home not found."
    if ($DryRun) {
        Write-Info "[dry-run] would install autoharness globally via '$InstallMethod' (out-of-cwd; a real run also requires the -Bootstrap opt-in)."
        return $AutoharnessHomeDefault
    }
    if (-not $Bootstrap) {
        Write-Warn2 "Global install is out-of-cwd and requires the explicit -Bootstrap opt-in. Re-run with -Bootstrap to install via '$InstallMethod', or set -Home / AUTOHARNESS_HOME to an existing install."
        return $null
    }

    switch ($InstallMethod) {
        "pip" {
            Write-Info "Installing autoharness via pip (global tool)..."
            & $PythonBin -m pip install --upgrade autoharness
        }
        "clone" {
            Write-Info "Cloning autoharness to $AutoharnessHomeDefault ..."
            & git clone https://github.com/softwaresalt/autoharness $AutoharnessHomeDefault
        }
    }
    $resolved = Resolve-AutoharnessHome
    if ($resolved) { Write-Ok "autoharness_home installed: $resolved"; return $resolved }
    Write-Fail "bootstrap failed: autoharness_home still unresolved after install."
    return $null
}

# ── Phase 3: register ───────────────────────────────────────────────────────
function Invoke-Register {
    Write-Phase "register"
    if ($Register -eq "none") { Write-Info "register skipped (-Register none)"; return $true }

    $cli = Get-Command autoharness -ErrorAction SilentlyContinue
    switch ($Register) {
        "vscode" { $cmd = "setup-vscode" }
        "copilot-cli" { $cmd = "plugin" }
        "claude" { $cmd = "setup-claude" }
        "codex" { $cmd = "setup-codex" }
    }

    if ($DryRun) {
        if ($Register -eq "copilot-cli") { Write-Info "[dry-run] would run: copilot plugin install autoharness@autoharness" }
        else { Write-Info "[dry-run] would run: autoharness $cmd" }
        return $true
    }

    try {
        if ($Register -eq "copilot-cli") {
            & copilot plugin install autoharness@autoharness
            if ($LASTEXITCODE -ne 0) { throw "copilot plugin install exited $LASTEXITCODE" }
        }
        elseif ($cli) {
            & $cli.Source $cmd
            if ($LASTEXITCODE -ne 0) { throw "autoharness $cmd exited $LASTEXITCODE" }
        }
        else {
            Write-Warn2 "autoharness CLI not on PATH; skipping register (run 'autoharness $cmd' after bootstrap)."
            return $true
        }
        Write-Ok "registered $Register environment"
        return $true
    } catch {
        Write-Fail "register failed: $_"
        return $false
    }
}

# ── Phase 4: scaffold ───────────────────────────────────────────────────────
function Invoke-Scaffold([string]$HomePath) {
    Write-Phase "scaffold"

    $selectedPacks = @()
    if ($Preset -eq "starter") {
        Write-Info "starter preset selected: no capability packs by default."
    }
    elseif ($Packs -eq "all") {
        $selectedPacks = @(Get-RegistryPacks $HomePath)
        if ($selectedPacks.Count -eq 0) {
            Write-Warn2 "Could not enumerate packs from the registry; writing config with no packs."
        } else {
            Write-Ok ("enumerated " + $selectedPacks.Count + " packs from registry")
        }
    }
    else {
        $registryPacks = @(Get-RegistryPacks $HomePath)
        foreach ($p in ($Packs -split ",")) {
            $p = $p.Trim()
            if (-not $p) { continue }
            if (($registryPacks.Count -gt 0) -and ($registryPacks -notcontains $p)) {
                Write-Fail "Unknown pack '$p' (not in registry)."
                return $false
            }
            $selectedPacks += $p
        }
    }

    $autoharnessDir = Join-Path $WorkspaceRoot ".autoharness"
    $configPath = Join-Path $autoharnessDir "config.yaml"

    $lines = @('schema_version: "1.0.0"', "preset: $Preset")
    if ($selectedPacks.Count -gt 0) {
        $lines += "capability_packs:"
        foreach ($p in $selectedPacks) { $lines += "  - $p" }
    } else {
        $lines += "capability_packs: []"
    }
    $configBody = ($lines -join "`n") + "`n"

    if ($DryRun) {
        Write-Info "[dry-run] would write $configPath with preset '$Preset' and $($selectedPacks.Count) packs."
        return $true
    }

    if (-not (Test-Path -LiteralPath $autoharnessDir)) {
        New-Item -ItemType Directory -Path $autoharnessDir -Force | Out-Null
    }

    if (Test-Path -LiteralPath $configPath -PathType Leaf) {
        $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
        $backup = "$configPath.$stamp.bak"
        Copy-Item -LiteralPath $configPath -Destination $backup -Force
        Write-Ok "backed up existing config to $backup"
        if (-not $Force) {
            Write-Warn2 "config.yaml exists; not overwriting without -Force (backup written). Re-run with -Force to replace."
            return $true
        }
    }

    Set-Content -LiteralPath $configPath -Value $configBody -NoNewline -Encoding utf8
    Write-Ok "wrote $configPath"

    $envLocalTarget = Join-Path $WorkspaceRoot ".env.local"
    if (Test-Path -LiteralPath $envLocalTarget -PathType Leaf) {
        Write-Info ".env.local present; left untouched (never clobbered)."
    }
    return $true
}

# ── Phase 5: compose (HANDOFF ONLY) ─────────────────────────────────────────
function Invoke-Compose {
    Write-Phase "compose (handoff)"
    Write-Info "Template composition is an AI-agent reasoning task and is NOT performed by this script."
    Write-Host ""
    Write-Host "  Next step — run the harness installer agent:" -ForegroundColor Yellow
    Write-Host "    /install-harness preset=$Preset" -ForegroundColor Yellow
    Write-Host ""
    Write-Info "The auto-mergeinstall agent will discover the workspace profile, compose templates, resolve variables, and run adversarial verification."
    return $true
}

# ── Phase 6: verify ─────────────────────────────────────────────────────────
function Invoke-Verify {
    Write-Phase "verify"
    $cli = Get-Command autoharness -ErrorAction SilentlyContinue
    if (-not $cli) {
        Write-Info "autoharness CLI not on PATH; skipping deterministic verify."
        return $true
    }
    $manifest = Join-Path $WorkspaceRoot ".autoharness/harness-manifest.yaml"
    if (-not (Test-Path -LiteralPath $manifest)) {
        Write-Info "no harness manifest yet (composition not run); skipping deterministic verify."
        return $true
    }
    if ($DryRun) {
        Write-Info "[dry-run] would run: autoharness verify-workspace --workspace $WorkspaceRoot"
        return $true
    }
    try {
        & $cli.Source verify-workspace --workspace $WorkspaceRoot
        if ($LASTEXITCODE -ne 0) { throw "verify-workspace exited $LASTEXITCODE" }
        Write-Ok "verify-workspace completed (see .autoharness reports)"
        return $true
    } catch {
        Write-Fail "verify failed: $_"
        return $false
    }
}

# ── Orchestration ───────────────────────────────────────────────────────────
Write-Host "autoharness deploy-harness — workspace: $WorkspaceRoot" -ForegroundColor Magenta
if ($DryRun) { Write-Host "DRY RUN — no mutations will be performed." -ForegroundColor Magenta }

if (-not (Invoke-Preflight)) { exit 1 }

$homePath = Invoke-Bootstrap
if (-not $homePath) { exit 2 }

if (-not (Invoke-Register)) { exit 3 }

if (-not (Invoke-Scaffold $homePath)) { exit 4 }

Invoke-Compose | Out-Null

if (-not (Invoke-Verify)) { exit 5 }

Write-Host ""
Write-Ok "deploy-harness completed. Run '/install-harness preset=$Preset' to compose the harness."
exit 0
