---
description: "Required protocol for Git merge, rebase, and rebase --onto workflows with conflict handling and stop controls"
---

# Git Merge and Rebase Instructions

## Required Protocol

### 1. Prepare the Workspace

* Confirm the working tree is clean with `git status --short`
* Stash local changes before proceeding
* Fetch latest remote refs

### 2. Select the Operation Path

* For merge: `git merge --no-edit {branch}`
* For rebase: `git rebase --empty=drop --reapply-cherry-picks {branch}`
* For rebase-onto: `git rebase --onto {onto} {upstream} {branch}`

### 3. Execute the Operation

* Run the planned Git command and capture output
* When Git reports conflicts, highlight the files listed by `git status --short`
* If no conflicts, jump to Step 6

### 4. Resolve Conflicts

* Inspect each conflicted file individually
* Apply focused edits to resolve markers, then stage changes
* After fixes, describe the rationale

### 5. Honor Review Pauses

* Pause after summarizing conflict fixes when requested
* Await explicit user confirmation before continuing

### 6. Continue or Complete

* Resume with `git merge --continue`, `git rebase --continue`, or abort if needed
* Confirm a clean tree after completion

### 7. Summarize Results

* Provide a summary of the operation, conflicts, and resolutions
* Remind the user no pushes were performed

## Guardrails

* Never push, force-push, or rewrite remote history
* Do not proceed with unrelated staged changes
* Document every conflict fix with justification
* When unsure, consult official Git documentation

Generated by autoharness | Template: git-merge.instructions.md.tmpl
