---
description: "TypeScript programming language coding conventions and best practices"
applyTo: '**/*.ts,**/*.tsx'
---

# TypeScript Instructions

Follow idiomatic TypeScript 5.x+ practices. These conventions enforce
type safety, consistent error handling, and maintainability.

## General Rules

* Enable `strict: true` in `tsconfig.json`. Never use `// @ts-ignore`
  or `as any` without a comment justifying the escape hatch.
* Prefer `const` over `let`; never use `var`.
* Use explicit return types on exported functions and methods.
* Write JSDoc or TSDoc comments on all exported functions, types,
  interfaces, and classes.
* Keep imports organized: external packages, internal modules, types.
* Prefer named exports over default exports for discoverability.

## Commands

```bash
npm test                               # Run all tests
npm run lint                           # ESLint check
npx prettier --check .                 # Format check
npx tsc --noEmit                       # Type check without emitting
npm run build                          # Build project
```

## Type Safety

* Use discriminated unions for state machines and tagged variants.
* Use `unknown` instead of `any` for values of uncertain type;
  narrow with type guards before use.
* Use `readonly` modifiers on properties that should not be mutated
  after construction.
* Use template literal types for constrained string patterns when
  appropriate.
* Prefer interfaces for object shapes; use type aliases for unions
  and computed types.

## Error Handling

* Define custom error classes extending `Error` with descriptive
  `name` properties and structured context.
* Use `try/catch` with typed catch blocks; avoid catching and
  silently discarding errors.
* Wrap errors with additional context:
  `throw new AppError("context", { cause: err })`.
* Use `Result<T, E>` patterns (or libraries like `neverthrow`) for
  functions with expected failure modes when appropriate.
* Never use exceptions for flow control.

## Async Patterns

* Use `async/await` over raw Promise chains.
* Always handle promise rejections — never leave floating promises.
* Use `AbortController` for cancellable operations.
* Use `Promise.allSettled` for concurrent independent operations
  where partial failure is acceptable.

## Testing

* Use colocated `.test.ts` or `.spec.ts` files for unit tests.
* Use `tests/integration/` for cross-module tests.
* Use `tests/contract/` for API and schema validation tests.
* Prefer `describe`/`it` structure with descriptive test names.
* Mock external dependencies at module boundaries, not deep internals.

## Anti-Patterns

* **`any` without justification**: Use `unknown` and narrow with
  type guards.
* **Non-null assertions (`!`)**: Prefer explicit null checks or
  optional chaining (`?.`).
* **Implicit `any` from missing types**: Enable `noImplicitAny`.
* **Barrel exports in large projects**: Can cause circular
  dependencies and slow builds.
* **Console.log for production logging**: Use a structured logger.
* **Mutable module-level state**: Use dependency injection or
  factory patterns.
* **String-based enums without validation**: Use `as const` objects
  or Zod schemas for runtime validation.

## Code Style

* Use Prettier for formatting with the project's configuration.
* Use ESLint with the project's ruleset.
* Prefer arrow functions for callbacks and short expressions.
* Use destructuring for function parameters when there are 3+
  related parameters.
* Keep files focused — one primary export per file when practical.

Generated by autoharness | Template: technology-typescript.instructions.md.tmpl
